"""Policy Protocol: bandit interface."""
from __future__ import annotations

from typing import Protocol, runtime_checkable
import numpy as np


@runtime_checkable
class Policy(Protocol):
    def predict(self, context: np.ndarray) -> str: ...
    def partial_fit(self, context: np.ndarray, arm: str, reward: float) -> None: ...
    def add_arm(self, arm: str) -> None: ...
    def snapshot(self) -> bytes: ...
    def restore(self, blob: bytes) -> None: ...
